version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "json"
        update-types: ["version-update:semver-major"]
    groups:
      ruby-production:
        dependency-type: production
        update-types: [minor, patch]
      ruby-development:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: npm
    directories:
      - "/"
      - "/docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      npm-production:
        dependency-type: production
        update-types: [minor, patch]
      npm-development:
        dependency-type: development
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      images:
        patterns: ["*"]
