default: &default
  adapter: postgresql
  encoding: unicode
  gssencmode: disable
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary: &primary_development
    <<: *default
    database: things_development
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USER", "things") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD", "things") %>
  cache:
    <<: *primary_development
    database: things_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: things_development_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: things_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *primary_development
    database: things_test
  cache:
    <<: *primary_development
    database: things_test_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: things_test_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: things_test_cable
    migrations_paths: db/cable_migrate

production:
  primary: &primary_production
    <<: *default
    database: things_production
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: things
    password: <%= ENV["THINGS_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: things_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: things_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: things_production_cable
    migrations_paths: db/cable_migrate
