default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      concurrency_maintenance_interval: 300
  workers:
    - queues: [sync, export, default]
      threads: 5
      processes: <%= ENV.fetch("BULK_CONCURRENCY", 1) %>
      polling_interval: 1

    - queues: analysis
      threads: <%= ENV.fetch("ANALYSIS_THREADS", 4) %>
      processes: <%= ENV.fetch("ANALYSIS_CONCURRENCY", 1) %>
      polling_interval: 2

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
