shared: &shared
  schedule_syncs:
    class: ScheduleSyncsJob
    queue: sync
    schedule: every minute
  sweep_audit_events:
    class: SweepAuditEventsJob
    queue: sync
    schedule: every day at 4am

development:
  <<: *shared

test: {}

production:
  <<: *shared
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
